

default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: racket

development:
  <<: *default
  database: ax_crm_dev

test:
  <<: *default
  database: ax_crm_test


production:
  <<: *default
  database: ax_crm_prod
